### ISSUE TITLE
software update.

### ISSUE THREAD

**Issue by moghribalakrishna** [GanuM/profitGuruPOS#551]
# Self update feature for ProfitGuru
### Tasks.
- [ ] Building versioning system for installers, using gulp bump/ semver.
- [ ] Migrating from tar to zip for compressing the installers, i.e. builder changes for all the profitGuru apps.
   **Details**
  Current targz and tar.gz npm modules shows random behaviour for untar operation and they does not work cross platform.
- [ ] Local installer Installer Publish server(i.e. To test the Updates locally rather then from cloud).
- [ ] Checking for new update downloading ,unzip and prepare for update.
- [ ] Informing user of new Updates using socket.io through client applications i.e. DAPP and MAPP.
- [ ] Install new update Upon action from the user.
- [ ] Display server version on DAPP and MAPP.
- [ ] Manage bad Updates.
- [ ] Open/Configurable/common code design to use it for tPGServerJs , terminal Server and even for DAPP update.
- 1) Making it configurable by using the config file from target updater.
- 2) Using Hooks to run external code during update process.
    **TODO postUpdateHook**
- [ ]  Back up before update.
- [ ] Implement Apis for exposing clients to get the current versions of the apps that its handling update for.
- [ ] Locking the servers during update and sending the Events for Restart to clients.
- [ ] Showing Update in progress for client apps.

**Comment by moghribalakrishna** [comment]
See if we can segregate the items which aren't covered and make the separate issues and take them on priority bases.
